services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  server:
    build: ./server
    container_name: inventory-server_container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://kanishkatharuka500:dTPVwACdN8lBoNVV@cluster0.7sbiyqh.mongodb.net/inventorydb
      - JWT_SECRET=supersecuretoken
    command: npm run dev

  client:
    build: ./client
    container_name: inventory-client_container
    ports:
      - "3000:3000"
    depends_on:
      - server
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_API_URL=http://server:5000
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  mongodb_data: